In [2]:
import numpy as np
import pandas as pd
from sklearn import model_selection

In [4]:
data = pd.read_csv('cust+data.csv',header=0,encoding='gb2312')
data.describe()

classes        term         limit   amt_in_acct  no_of_loan  \
count  841.000000  841.000000  8.410000e+02  8.410000e+02  841.000000   
mean     2.816885  188.594530  2.562838e+05  2.317469e+05    1.001189   
std      1.194133   98.102077  1.844475e+05  1.731071e+05    0.034483   
min      1.000000   24.000000  3.000000e+04  7.606080e+03    1.000000   
25%      2.000000  120.000000  1.400000e+05  1.185635e+05    1.000000   
50%      3.000000  180.000000  2.100000e+05  1.899473e+05    1.000000   
75%      4.000000  252.000000  3.300000e+05  3.129751e+05    1.000000   
max      5.000000  360.000000  2.000000e+06  1.853406e+06    2.000000   

       credit_level         age  monthly_saving  monthly_investment  \
count    841.000000  841.000000      841.000000               841.0   
mean       3.973841   37.978597     1319.501867                 0.0   
std        0.805801    9.261519    10383.129958                 0.0   
min        2.000000   21.000000        0.000000                 0.0   
25%        3.000000   30.000000        0.000000                 0.0   
50%        4.000000   36.000000        7.490000                 0.0   
75%        5.000000   45.000000      152.370000                 0.0   
max        6.000000   62.000000   232943.490000                 0.0   

       monthly_insurance  
count         841.000000  
mean          121.284185  
std          1954.125372  
min             0.000000  
25%             0.000000  
50%             0.000000  
75%             0.000000  
max         48000.000000

In [5]:
#各个列没有区分度  直接删除
data['monthly_investment'].unique()

array([0], dtype=int64)

In [7]:
data.drop(['monthly_investment'],axis=1,inplace=True)

In [8]:
data.describe()

classes        term         limit   amt_in_acct  no_of_loan  \
count  841.000000  841.000000  8.410000e+02  8.410000e+02  841.000000   
mean     2.816885  188.594530  2.562838e+05  2.317469e+05    1.001189   
std      1.194133   98.102077  1.844475e+05  1.731071e+05    0.034483   
min      1.000000   24.000000  3.000000e+04  7.606080e+03    1.000000   
25%      2.000000  120.000000  1.400000e+05  1.185635e+05    1.000000   
50%      3.000000  180.000000  2.100000e+05  1.899473e+05    1.000000   
75%      4.000000  252.000000  3.300000e+05  3.129751e+05    1.000000   
max      5.000000  360.000000  2.000000e+06  1.853406e+06    2.000000   

       credit_level         age  monthly_saving  monthly_insurance  
count    841.000000  841.000000      841.000000         841.000000  
mean       3.973841   37.978597     1319.501867         121.284185  
std        0.805801    9.261519    10383.129958        1954.125372  
min        2.000000   21.000000        0.000000           0.000000  
25%        3.000000   30.000000        0.000000           0.000000  
50%        4.000000   36.000000        7.490000           0.000000  
75%        5.000000   45.000000      152.370000           0.000000  
max        6.000000   62.000000   232943.490000       48000.000000

In [9]:
# monthly_insurance 只有几个取值 处理方案  二值化 >0当1  否则为0

In [10]:
data['monthly_insurance'].unique()

array([    0,  4000, 10000, 20000, 48000], dtype=int64)

In [12]:
data['monthly_insurance']=data['monthly_insurance'].map(lambda x: int(x>0))
data['monthly_insurance'].unique()

array([0, 1], dtype=int64)

In [14]:
data['monthly_insurance'][0:5]

0    0
1    0
2    0
3    0
4    0
Name: monthly_insurance, dtype: int64