In [6]:
#定义一个类 car
class Car:
    #成员方法
    def infor(self):
        print('这是一辆车...')
car=Car()
car.infor()

这是一辆车...


In [8]:
#使用内置函数来判断这些类型
print( isinstance(car,Car))
print( isinstance(car,str))


True
False


In [9]:
#可以使用pass 来表达空语句
class A:
    pass

class B:
    pass
def c():
    pass

if 5>3:
    pass

In [15]:
#self相当于java中对象中的this，表示指向对象自身的引用
#在python中  实例方法的第一个参数必须是self

class TestA:
    def __init__(self,v): #__init__(self,...)   构造方法，由于python运行环境来调用
        self.value=v  #this.value=v
        print('您的名字：',self.value)
    def show(b,name):  #self 的名字不一定要是self，但这个方法第一个参数一定是要self
        b.name=name
        print('您的名字：',b.name)
        
aa=TestA('abc')
aa.show('zy')


您的名字： abc
您的名字： zy


In [18]:
#属性：实例属性（由对象名调用）  类属性（静态属性 static）
class Car:
    price=10000  #类属性
    def __init__(self,v):
        self.color=v
        
c1=Car('red')
print(c1.color,c1.price,Car.price)  #  静态属性可以由对象名调用  也可以由类名直接调用
# print(Car.color)  错误

red 10000 10000


In [19]:
# 动态添加的属性
Car.name='上海大众'  #添加了一个静态属性
print(Car.name)

上海大众


In [20]:
print(c1.name)

上海大众


In [22]:
c1.gas=100   #动态添加实例属性
print(c1.gas)   #动态添加的实例属性只能由它本身去调用  类名 或者其他对象都不能调用
c2=Car('bule')
print(c2.gas)

100


AttributeError: 'Car' object has no attribute 'gas'

In [25]:
#动态添加方法
import types

#定义一个函数
def setSpeed(self,value):
    self.speed=value
    
# MethodType作用，是将  一个方法绑定一个对象  类似java反射
c1.setSpeed2=types.MethodType(setSpeed,c1) # 给c1对象里面添加setSpeed方法
#下面调用的方法 setSpeed2
c1.setSpeed2(150)

print(c1.speed)


#c2是无法调用这个方法的
c2.setSpeed2(150)
print(c2.speed)

150


AttributeError: 'Car' object has no attribute 'setSpeed2'

In [29]:
class Person:
    def __init__(self,name):
        self.name=name
    def sing(self):
        print(self.name,'唱歌')
    
def walk(self):
    print(self.name,"走路")

    
p1=Person('代智博')
p1.sing()
p1.walk=types.MethodType(walk,p1)
p1.walk()

代智博 唱歌
代智博 走路


In [1]:
'''
_xxx:受保护成员，不能用'from module import *导入'
__xxx__:系统定义的特殊成员；__init__()  __call__()  python的编译器调用  回调函数
___xxx:私有成员，只有类对象自己能访问，子类对象不能直接访问到这个成员，但在对象外部可以通过'对象名.__类名__xxx'这样的特殊方式访问
'''

"\n_xxx:受保护成员，不能用'from module import *导入'\n__xxx__:系统定义的特殊成员；__init__()  __call__()  python的编译器调用  回调函数\n___xxx:私有成员，只有类对象自己能访问，子类对象不能直接访问到这个成员，但在对象外部可以通过'对象名.__类名__xxx'这样的特殊方式访问\n"

In [2]:
class A:
    def __init__(self,value1=0,value2=0):
        self._value1=value1  #受保护成员
        self.__value2=value2  #私有
        
    def setValue(self,value1,value2):
        self._value1=vlaue1
        self.__value2=value2
        
    def show(self):
        print( self._value1)
        print( self.__value2)
        
a=A()
print(a._value1)  #在类的外部访问
print(a.__value2)  #在类的外部访问私有成员是不行的

0


AttributeError: 'A' object has no attribute '__value2'

In [7]:
class Fruit:
    def __init__(self):
        self.__color='red'  #私有成员
        self.price=1  #公有
        
apple=Fruit()
print(apple.price)
apple.price=10
print(apple.price)


#print( apple.__color)  #私有成员外部无法访问
print(apple._Fruit__color)  #在外部要访问可以通过  '对象名._类名__xxx'  这样子特殊方式来访问
apple._Fruit__color='blue'
print(apple._Fruit__color)  #python里面对权限的控制不严格


1
10
red
blue


In [8]:
#  python 的下划线
'''
1.在交互编程环境下 ，  _表示解释器中最后一次的输出内容
'''

'\n1.在交互编程环境下 ，  _表示解释器中最后一次的输出内容\n'

In [9]:
3+5

8

In [10]:
_*3

24

In [12]:
'''
2.程序里面  _表示不关心该变量的值
'''
for _ in range(5):
    print(3,end=' ')

3 3 3 3 3 

In [17]:
'''
python 的方法种类： 公有方法 私有方法  静态方法  类方法
静态方法与类方法都可以通过类名对象调用  但不能直接访问  属于对象的成员  只能访问类的成员
静态方法可以没有参数
'''

class Root:
    __total=0 #类成员
    def __init__(self,v):  #构造方法
        self.__value=v  #私有属性
        Root.__total+=1
        
    def show(self):
        print( self.__value)
        print( Root.__total)
    
    @classmethod   
    def classShowTotal(cls):  #类方法  cls是类的类名
        print( cls.__total)
        
    @staticmethod   #静态方法
    def staticShowTotal( ):
        print( Root.__total)

        
r=Root(3 )
r.classShowTotal()
r.staticShowTotal()
r.show()
rr=Root(5)
rr.show()
Root.classShowTotal()
Root.staticShowTotal()

1
1
3
1
5
2
2
2


# 项目案例

In [ ]:
#1.自定义数组 在myarray.py文件中 ，定义了一个数组类，重写了一部分特殊方法以支持数组之间
#数组与整数之间的四则运算以及内积，大小比较，成员测试和元素访问等运算符.

In [ ]:
class MyArray:
    '''
    一个自定义的数组，它存数字
    '''
    def __isNumber(self,n):  #私有方法  帮助方法
        return isinstance( n,(int,float,complex)  )
    
    def __init__(self,*args):  #列表类型
        #假如没有实参  则创建一个空的数组
        if not args:
            self.__value=[]  # __value  说明是私有  self是对象的成员
        else:
            #类型检测
            for arg in args:
                if not self.__inNumber( arg ):
                    print('成员必须是数字')
                    return
            self.__value=list(args)  # list() 是一个内置python函数 用于强制类型的转换
    
    #重载运算符  +
    #1.  myArray+2  将数字中的每个元素与数字相加
    #2.  myArray+myArray2  将2个数组相应的元素相加，返回一个新的数组
    def __add__(self,n):
        if self.__isNumber(  n):
            #数组中的每个元素与n相加
            b=MyArray()
            b.__value=[item+n  for item in self.__value]
            return b
        elif isinstance(n,MyArray):
            # self.__value.append( n.__value)  做法 完成拼凑
            if len( n.__value)=len(self.__value):
                c=MyArray()
                c.__value=[ i+j  for i,j in zip(self.__value,n.__value)   ]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
            
    #重载运算符  -
    #1.  myArray-2  将数字中的每个元素与数字相减
    #2.  myArray-myArray2  将2个数组相应的元素相减，返回一个新的数组
    def __sub__(self,n):
        if self.__isNumber( n):
            #数组中的每个元素与n相减
            b=MyArray()
            b.__vlaue=[item-n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
             # self.__value.append( n.__value)  做法 完成拼凑
            if len( n.__value)=len(self.__value):
                c=MyArray()
                c.__value=[ i-j  for i,j in zip(self.__value,n.__value)   ]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
        
    #   *运算    
        
    def __mul__(self,n):
        if self.__isNumber(  n):
            b=MyArray()
            b.__value=[item*n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
            if len(n.__value) =len(self.__value):
                c=MyArray()
                c.__value=[ i*j for i,j in zip(self.__value,n.__value)]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
            
            
    #  / 运算
    
     def __truediv__(self,n):
        if self.__isNumber(  n):
            b=MyArray()
            b.__value=[item/n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
            if len(n.__value) =len(self.__value):
                c=MyArray()
                c.__value=[ i/j for i,j in zip(self.__value,n.__value)]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
            
    def __floordiv__(self,n):
        if self.__isNumber( n ):
            b=MyArray()
            b.__value=[item//n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
            if len(n.__value) =len(self.__value):
                c=MyArray()
                c.__value=[ i//j for i,j in zip(self.__value,n.__value)]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
    
    
    #**
    def  __pow__(self,n):
        if self.__isNumber( n ):
            b=MyArray()
            b.__value=[item**n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
            if len(n.__value) =len(self.__value):
                c=MyArray()
                c.__value=[ i**j for i,j in zip(self.__value,n.__value)]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')    
            
    def __mod__(self,n):
        if self.__isNumber(n):
            b=MyArray()
            b.__value=[item%n for item in self.__value]
            return b
        elif isinstance( n,MyArray):
            if len(n.__value) =len(self.__value):
                c=MyArray()
                c.__value=[ i%j for i,j in zip(self.__value,n.__value)]
                return c
            else:
                print('待操作的数组长度不一样，不能运算')
        else:
            print('不支持本类型的数据操作')
    
    #返回的是字节长，而不是数据长  更改了  len(MyArray) 求长度的意义
    def __len__(self):   #  len(MyArray)
        if isinstance(self.__value[0],int):
            return len(self.__value)*4
        elif isinstance(self.__value[0],float):
            return len(self.__value)*8
        elif isinstance(self.__value[0],complex):
            return len(self.__value)*16
        
    def __str__(self):  # str(MyArray)
        return 'zy的MyArray：'+str(self.__value)
    
    def append(self,v):
        assert self.__isNumber( v )
        self.__value.append(v)
    
    def __getitem__(self,index):  #myarray[0]  ->  __getitem__()
        length=len(self.__value)
        if isinstance(index,int) and 0<=index<length:
            return self.__value[index]
        elif isinstance(index,(list,tuple)):  #myarray[（1,2,3）] or myarray[[1,2,3]]
            result=[]
            for i in index:
                if not (isinstance(i,int)):
                    return '索引不是数字'
                if i<0 or i>=length:
                    return '索引越界'
                result.append( self.__value[i])
            return result
        else:
            return '索引的数据类型暂时不支持'
    
    def __setitem__(self,index,value):
    

In [1]:
#  关键字 with 的类
# 它实现了两个特殊  ：  __enter__()   __exit__()
class MyHello:
    def __init__(self):
        print('这是myhello的构造')
        
    def __enter__(self):
        print('执行了enter')
    
    def __exit__(self,exceptionType,exceptionVal,trace):
        print('执行了exit')
        
with MyHello() as mh:  #产生一个容器
    print('1+1')

这是myhello的构造
执行了enter
1+1
执行了exit


In [ ]:
# with 的应用

In [3]:
#传统文件的操作
fr=open('readme.txt','r')
lines=fr.readlines()
print( lines )
fr.close()

UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 14: illegal multibyte sequence

In [6]:
class MyFileOpen:  #定义一个生命周期控制
    def __init__(self,filename,mode):
        self.fp=open(filename,mode)
    def __enter__(self):
        return self.fp
    def __exit__(self,exceptionType,exceptionVal,trace):
        self.fp.close()
        
with MyFileOpen('readme.txt','r') as fp:
    lines=fp.readlines()
    print( lines )

UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 14: illegal multibyte sequence

# 课后作业 常用的数据结构的定义

In [ ]:
'''
案例二：自定义实现集合，模拟python内置集合类型（set），实现元素的添加，删除，以及并集，交集，对称差集等基本运算
1.无序，不可重复  2.可集合运算 3.元素是可哈希
'''

In [11]:
class MySet:
    
    def __init__(self,data=None):
        '''
        初始化这个集合
        '''
        if data==None:
            self.__data=[]
        else:
            if not hasattr(data,'__iter__'):
                raise Exception('必须提供可迭代的数据类型')
            temp=[]
            for item in data:
                hash (item)
                if not item in temp:
                    temp.append(item)
            self.__data=temp
        
    #析构方法
    def __del__(self):
        del self.__data
        
    #添加
    def add(self,value):
        hash(value)
        if value not in self.__data:
            self.__data.append(value)

            
    #删除
    def remove(self,value):
        if value in self.__data:
            self.__data.remove(value)
            print('删除',value,'成功')
        else:
            print('元素',value,'不存在')
    
    #随机弹出并返回一个元素
    def pop(self):
        if not self.__data:
            print('集合已经空，弹出操作被忽略')
            return 
        import random  
        item=random.choice(self.__data )
        self.__data.remove(item)
        return item
    
    #运算符重载 差集运算
    def __sub__(self,anotherset):
        if not isinstance(anotherset,MySet ):
            raise Exception('类型不匹配，不能进行差集运算')
        result=MySet()
        for item in self.__data:
            if item not in anotherset.__data:
                result.__data.append(item)
        return result
    
 
    
    
    def differe(self,anotherset):
        return self-anotherset
    
    #运算符重载  并集 |
    def __or__(self,anotherset):
        if not isinstance(anotherset,MySet):
            raise Exception('类型不匹配，不能并集运算')
        result=MySet(self.__data )
        for item in anotherset.__data:
            if item not in result.__data:
                result.__data.append(item)
        return result
    
    def union(self,anotherset):
        return self|anotherset
    
    # 交集运算  &
    def __and__(self,anotherset):
        if not isinstance(anotherset,MySet):
            raise Exception('类型不匹配，不能并集运算')
        result=MySet()
        for item in anotherset.__data:
            if item in self.__data:
                result.__data.append(item)
        return result
                
    
    
    def intersection(self,anotherset):
        return self&anotherset
    
    #对称差分
    def __xor__(self,anotherset):
        return (self-anotherset)|(anotherset-self)
    
    def symmetric_difference(self,anotherset):
        return self^anotherset
            
    #相等 ==
    def __eq__(self,anotherset):
        if not isinstance( anotherset,MySet):
            raise Exception('类型不匹配，不能进行相等运算')
        return sorted(self.__data)==sorted(anotherset.__data)
    
    # > :1 不能相等  self 中有元素没有在another中出现 且 anotherset的全部元素都在self出现过
    def __gt__(self,anotherset):
        if not isinstance(anotherset,MySet):
            raise Exception('类型不匹配，不能进行>运算')
        if self!=anotherset:
            flag1=True
            for item in self.__data:
                if item not in anotherset.__data:
                    flag1=False
                    break
            flag2=True
            for item in anotherset.__data:
                if item not in self.__data:
                    flag2=False
                    break
            if not flag1 and flag2:
                return True
        return False
    
    def __ge__(self,anotherset):
        if not isinstance(anotherset,MySet):
            raise Exception('类型不匹配，不能进行>=运算')
        return self==anotherset or self >anotherset
                    
    
    def __str__(self):
        result=str(self.__data)
        result=result[1:len(result)-1]
        return '{'+result+'}'
    
    #重写了 tostring
    __repr__=__str__

In [14]:
ms=MySet()
ms2=MySet( (1,2,3,4,4,4) )
print(ms2)
ms2.add(44)
ms2.remove(44)

{1, 2, 3, 4}
删除 44 成功


In [15]:
print(ms2.pop() )
ms1=MySet( (2,3) )
ms2-ms1

2


{1, 4}

In [8]:
class MyStack:
    def __init__(self,size=10):
        '''创建栈对象并进行初始化，默认栈的大小为10'''
        #使用列表来存放栈的元素
        self._content =[]
        #初始化大小
        self._size=size
        #栈中的元素个数初始化为0
        self._current=0
    
    def empty(self):
        '''清空栈'''
        self._content = []
        self._current = 0
    
    def isEmpty(self):
        '''测试栈是否为空'''
        return not self._content
    
    def setSize(self,size):
        '''调整栈的大小，可以增大或者缩小空间'''
        #如果缩小空间时指定的新的大小，小于已有的元素
        #删除除指定的大小以外的元素
        if size < self._current:
            for i in range(size,self._current)[::-1]:
                del self._content[i]
            self._current=size
        self._size=size
        
    def isFull(self):
        '''测试栈是否已满'''
        return self._current==self._size
    
    def push(self,v):
        '''将新元素入栈'''
        #模拟入栈  需要先测试栈是否已经满
        if self._current < self._size:
            self._content.append(v)
            #栈中的元素加一
            self._current += 1
        else:
            print('栈已经满了！！')
    
    def __str__(self):
        return str(self._content)
    
    __repr__=__str__
    
    def pop(self):
        '''将栈顶元素出栈'''
        #模拟出栈  需要先测试栈是否为空
        if self._content:
            #栈中的元素个数减1
            self._current-=1
            return self._content.pop()
        else:
            print('栈是空的删不了')
    
    def show(self):
        '''展示栈里面的所有元素对象'''
        print(self._content)
        
    def showRemainderSpace(self):
        '''显示栈的对象剩余空间大小'''
        print('栈还可以存',self._size - self._current,'个元素')

In [9]:
s=MyStack()
s.push(1)
s.push(2)
s.show()

[1, 2]


案例四  自定义队列的结构  实现入队 出队的操作 提供超时功能

In [17]:
import time

class MyQueue:
    def __init__(self,size=10):
        self.__content=[]
        self.__size=size
        self.__current=0
        
    def resize(self,size):
        if size < self.__current:
            #收缩队列删除后面的元素  [5,10] ->[5,6,7,8,9][::-1]
            for i in range(size,self.__current)[::-1]:
                del self.__content[i]
            self.__current=size
        self.__size=size
    
    def enqueue(self,v,timeout=5 ):
        '''
        模拟入队，在队列尾部添加元素
        满了 就阻塞，直到超时
        '''
        for i in range( timeout ):
            if self.__current < self.__size:
                self.__content.append(v)
                self.__current = self.__current + 1
                break
            time.sleep(1)
        else:
            return '队列已经存满，操作超时，放弃....'
        
    def dequeue(self,timeout=5):
        for i in range(timeout):
            if self.__content:
                self.__current = self.__current - 1
                return self.__content.pop( 0 )
            time.sleep(1)
        else:
            return '队列为空，操作超时，放弃出队....'
        
    def clear(self ):
        self.__content=[]
        self.__current=0
    
    def isEmpty(self):
        return not self.__content
    
    def isFull(self):
        return self.__current==self.__size
    
    def show(self):
        if self.__current >0:
            for i in self.__content:
                print( i )
        else:
            print('你是空的')

In [18]:
q=MyQueue()
q.enqueue(1)
q.enqueue(2)
q.enqueue(3)

q.show()


1
2
3


 案例5   数

In [19]:
#创建这棵树，存数据 遍历（前序，中序，后序）
class MyTree:
    def __init__(self,value):
        self.__left=None
        self.__rigth=None
        self.__value=value
    
    def insertLeftChild(self,value):
        if self.__left:
            print('左子树已经存在....')
        else:
            self.__left=MyTree(value)
            return self.__left
        
    def insertRightChild(self,value):
        if self.__rigth:
            print('右子树已经存在....')
        else:
            self.__rigth=MyTree(value)
            return self.__rigth
    
    #前序遍列
    def preOrder(self):
        print( self.__value )
        if self.__left:
            self.__left.preOrder()
        if self.__rigth:
            self.__rigth.preOrder()
            
    #后序遍历
    def postOrder(self):
        if self.__left:
            self.__left.postOrder()
        if self.__rigth:
            self.__rigth.postOrder()
        print( self.__value )
        
    #中序遍历
    def inOrder(self):
        if self.__left:
            self.__left.inOrder()
        print(self.__value)
        if self.__rigth:
            self.__rigth.inOrder()

In [20]:
t=MyTree(1)
left=t.insertLeftChild( 0 )
left.insertLeftChild( -2 )
left.insertRightChild( -1 )
right=t.insertRightChild(2)

t.inOrder()
'''
         1
      0    2
              
    -2 -1   

'''

-2
0
-1
1
2


In [21]:
#矩阵运算
import numpy as np
x=np.arange(8)
print(x)
print(x.reshape( (2,4) ) )
y=x.reshape( (2,4)  )
print( y.T )


print(y+3)

z=np.arange(8)
zz=z.reshape( (2,4) )
print(y+zz)

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]
[[ 3  4  5  6]
 [ 7  8  9 10]]
[[ 0  2  4  6]
 [ 8 10 12 14]]
