In [1]:
import numpy as np

In [2]:
a=np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
#展平
a.flatten()  #返回一个展平后的结果

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
print(a)  #但没有改变 a 的shape

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
a.shape=(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
# 转置矩阵
a.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [9]:
a.transpose()

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [10]:
a.resize(2,12)   #resize是对原数组进行修改
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
#类型的转换
#1.将一个ndarray转为python的基本数据类型 list
print(type(a))
print(type(a.tolist()))

<class 'numpy.ndarray'>
<class 'list'>


In [12]:
#将这个ndarray中的值的数据类型进行转换
print(a.astype(float))

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
 [ 12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.]]


In [17]:
# stacking 组合
a=np.arange(9).reshape(3,3)
b=2*a
print(a)
print(b)
print('=========水平组合：行数不变，增加列数=========')
#对于一维数组将按列组合
oned=np.arange(2)
print(oned)
twod=2*oned
print(twod)
print(np.column_stack((oned,twod)))
#对于二维数组，行数不变，增加列数
print( np.column_stack((a,b)))
print(np.hstack((a,b)))
print(np.concatenate((a,b),axis=1))

print('=========垂直组合：行数增加，列数不变=========')
#对于一维数组按行组合
print(np.row_stack((oned,twod)))
#对于二维数组：行数增加 列数不变
print(np.row_stack((a,b) ) )
print(np.vstack((a,b) ) )
print(np.concatenate((a,b),axis=0 ) )
print('==========深度组合=========')
print(np.dstack((a,b) ) )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
=========水平组合：行数不变，增加列数=========
[0 1]
[0 2]
[[0 0]
 [1 2]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
=========垂直组合：行数增加，列数不变=========
[[0 1]
 [0 2]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
==========深度组合=========
[[[ 0  0]
  [ 1  2]
  [ 2  4]]

 [[ 3  6]
  [ 4  8]
  [ 5 10]]

 [[ 6 12]
  [ 7 14]
  [ 8 16]]]


In [22]:
#=====================分割数组=========
#   hsplit   vsplit  dsplit split
print('=========沿着水平方向分割=========')   #其实就是垂直于水平分割
print(a)
print(np.hsplit(a,3))
print('=========沿着垂直方向分割=========')  #其实就是垂直于垂直方向分割
print(np.vsplit(a,3))
print('=========沿着深度方向分割=========')
# print(np.dsplit(a,3))    二维数组是无法完成深度分割
c=np.arange(27).reshape(3,3,3)
print(c)
print(np.dsplit(c,3))

=========沿着水平方向分割=========
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]
=========沿着垂直方向分割=========
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
=========沿着深度方向分割=========
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[ 0],
        [ 3],
        [ 6]],

       [[ 9],
        [12],
        [15]],

       [[18],
        [21],
        [24]]]), array([[[ 1],
        [ 4],
        [ 7]],

       [[10],
        [13],
        [16]],

       [[19],
        [22],
        [25]]]), array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])]
