# 1.方差选择法：
使用方差作为特征评分标准，如果某个特征的取值差异不大，通常认为该特征对区分样本的贡献度不大
因此在构造特征过程中去掉方差小于阈值的特征


In [1]:
#特征选择----方差选择法
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1)

In [2]:
from sklearn.datasets import load_iris
iris=load_iris()
print('iris特征名称',iris.feature_names)
print('iris特征矩阵',iris.data)


iris特征名称 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
iris特征矩阵 [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [

In [3]:
#特征选择--方差选择法
from sklearn.feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=1) # threshold 为方差的阈值  默认0
selectedData=vt.fit_transform(iris.data)
print('方差选择法的特征：',selectedData)

方差选择法的特征： [[ 1.4]
 [ 1.4]
 [ 1.3]
 [ 1.5]
 [ 1.4]
 [ 1.7]
 [ 1.4]
 [ 1.5]
 [ 1.4]
 [ 1.5]
 [ 1.5]
 [ 1.6]
 [ 1.4]
 [ 1.1]
 [ 1.2]
 [ 1.5]
 [ 1.3]
 [ 1.4]
 [ 1.7]
 [ 1.5]
 [ 1.7]
 [ 1.5]
 [ 1. ]
 [ 1.7]
 [ 1.9]
 [ 1.6]
 [ 1.6]
 [ 1.5]
 [ 1.4]
 [ 1.6]
 [ 1.6]
 [ 1.5]
 [ 1.5]
 [ 1.4]
 [ 1.5]
 [ 1.2]
 [ 1.3]
 [ 1.5]
 [ 1.3]
 [ 1.5]
 [ 1.3]
 [ 1.3]
 [ 1.3]
 [ 1.6]
 [ 1.9]
 [ 1.4]
 [ 1.6]
 [ 1.4]
 [ 1.5]
 [ 1.4]
 [ 4.7]
 [ 4.5]
 [ 4.9]
 [ 4. ]
 [ 4.6]
 [ 4.5]
 [ 4.7]
 [ 3.3]
 [ 4.6]
 [ 3.9]
 [ 3.5]
 [ 4.2]
 [ 4. ]
 [ 4.7]
 [ 3.6]
 [ 4.4]
 [ 4.5]
 [ 4.1]
 [ 4.5]
 [ 3.9]
 [ 4.8]
 [ 4. ]
 [ 4.9]
 [ 4.7]
 [ 4.3]
 [ 4.4]
 [ 4.8]
 [ 5. ]
 [ 4.5]
 [ 3.5]
 [ 3.8]
 [ 3.7]
 [ 3.9]
 [ 5.1]
 [ 4.5]
 [ 4.5]
 [ 4.7]
 [ 4.4]
 [ 4.1]
 [ 4. ]
 [ 4.4]
 [ 4.6]
 [ 4. ]
 [ 3.3]
 [ 4.2]
 [ 4.2]
 [ 4.2]
 [ 4.3]
 [ 3. ]
 [ 4.1]
 [ 6. ]
 [ 5.1]
 [ 5.9]
 [ 5.6]
 [ 5.8]
 [ 6.6]
 [ 4.5]
 [ 6.3]
 [ 5.8]
 [ 6.1]
 [ 5.1]
 [ 5.3]
 [ 5.5]
 [ 5. ]
 [ 5.1]
 [ 5.3]
 [ 5.5]
 [ 6.7]
 [ 6.9]
 [ 5. ]
 [ 5.7]
 [ 4.9]
 [ 6.7]
 [ 4.9

In [4]:
print(vt.variances_)

[ 0.68112222  0.18675067  3.09242489  0.57853156]


In [11]:
#加载数据
from sklearn.datasets import load_iris
iris=load_iris()
#特征选择
from sklearn.feature_selection import SelectKBest,SelectPercentile
from sklearn.feature_selection import chi2

#skb=SelectPercentile(chi2,50)
skb=SelectKBest(chi2,k=2)
new_data=skb.fit_transform(iris.data,iris.target)
print(new_data)
print(skb.scores)

[[ 1.4  0.2]
 [ 1.4  0.2]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.7  0.4]
 [ 1.4  0.3]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.5  0.2]
 [ 1.6  0.2]
 [ 1.4  0.1]
 [ 1.1  0.1]
 [ 1.2  0.2]
 [ 1.5  0.4]
 [ 1.3  0.4]
 [ 1.4  0.3]
 [ 1.7  0.3]
 [ 1.5  0.3]
 [ 1.7  0.2]
 [ 1.5  0.4]
 [ 1.   0.2]
 [ 1.7  0.5]
 [ 1.9  0.2]
 [ 1.6  0.2]
 [ 1.6  0.4]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.6  0.2]
 [ 1.6  0.2]
 [ 1.5  0.4]
 [ 1.5  0.1]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.2  0.2]
 [ 1.3  0.2]
 [ 1.5  0.1]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.3  0.3]
 [ 1.3  0.3]
 [ 1.3  0.2]
 [ 1.6  0.6]
 [ 1.9  0.4]
 [ 1.4  0.3]
 [ 1.6  0.2]
 [ 1.4  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 4.7  1.4]
 [ 4.5  1.5]
 [ 4.9  1.5]
 [ 4.   1.3]
 [ 4.6  1.5]
 [ 4.5  1.3]
 [ 4.7  1.6]
 [ 3.3  1. ]
 [ 4.6  1.3]
 [ 3.9  1.4]
 [ 3.5  1. ]
 [ 4.2  1.5]
 [ 4.   1. ]
 [ 4.7  1.4]
 [ 3.6  1.3]
 [ 4.4  1.4]
 [ 4.5  1.5]
 [ 4.1  1. ]
 [ 4.5  1.5]
 [ 3.9  1.1]
 [ 4.8  1.8]
 [ 4.   1.3]
 [ 4.9  1.5]
 [ 4.7  1.2]
 [ 4.3  1.3]
 [ 4.4  1.4]
 [ 4.8  1.4]

AttributeError: 'SelectKBest' object has no attribute 'scores'

单变量特征选择：
采用皮尔逊相关系数（相关法）（回归问题）
使用 pearson 系数作为特征评分标准
相关系数绝对值越大，相关性越强(相关系数越接近于1或者-1时，相关性越强；越接近0越弱)
皮尔逊能够衡量线性相关的特征集

In [14]:
#载入数据
from sklearn.datasets import load_iris
irisdata=load_iris()

#特征选择（皮尔逊）
from sklearn.feature_selection import SelectKBest
from scipy.stats import pearsonr  #计算皮尔逊相关系数
import numpy as np

In [16]:
skb=SelectKBest(lambda X,Y: tuple(map(tuple,array(list(map(lambda x:pearsonr(x,Y),x.T) ) ).T ) ),k=2 )
newData=skb.fit_transform(irisdata.data,irisdata.target)
print(skb.scores_)
print(newData)

[  10.81782088    3.59449902  116.16984746   67.24482759]
[[ 1.4  0.2]
 [ 1.4  0.2]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.7  0.4]
 [ 1.4  0.3]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.5  0.2]
 [ 1.6  0.2]
 [ 1.4  0.1]
 [ 1.1  0.1]
 [ 1.2  0.2]
 [ 1.5  0.4]
 [ 1.3  0.4]
 [ 1.4  0.3]
 [ 1.7  0.3]
 [ 1.5  0.3]
 [ 1.7  0.2]
 [ 1.5  0.4]
 [ 1.   0.2]
 [ 1.7  0.5]
 [ 1.9  0.2]
 [ 1.6  0.2]
 [ 1.6  0.4]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 1.6  0.2]
 [ 1.6  0.2]
 [ 1.5  0.4]
 [ 1.5  0.1]
 [ 1.4  0.2]
 [ 1.5  0.1]
 [ 1.2  0.2]
 [ 1.3  0.2]
 [ 1.5  0.1]
 [ 1.3  0.2]
 [ 1.5  0.2]
 [ 1.3  0.3]
 [ 1.3  0.3]
 [ 1.3  0.2]
 [ 1.6  0.6]
 [ 1.9  0.4]
 [ 1.4  0.3]
 [ 1.6  0.2]
 [ 1.4  0.2]
 [ 1.5  0.2]
 [ 1.4  0.2]
 [ 4.7  1.4]
 [ 4.5  1.5]
 [ 4.9  1.5]
 [ 4.   1.3]
 [ 4.6  1.5]
 [ 4.5  1.3]
 [ 4.7  1.6]
 [ 3.3  1. ]
 [ 4.6  1.3]
 [ 3.9  1.4]
 [ 3.5  1. ]
 [ 4.2  1.5]
 [ 4.   1. ]
 [ 4.7  1.4]
 [ 3.6  1.3]
 [ 4.4  1.4]
 [ 4.5  1.5]
 [ 4.1  1. ]
 [ 4.5  1.5]
 [ 3.9  1.1]
 [ 4.8  1.8]
 [ 4.   1.3]
 [ 4.9