In [1]:
#train_test_split
from sklearn.model_selection import train_test_split,KFold,StratifiedKFold,LeaveOneOut,cross_val_score
import numpy as np
def test_train_test_split():
    '''
    测试 train_test_split 的用法
    
    '''
    X=[[1,2,3,4],
       [11,12,13,14],
       [21,22,23,24],
       [31,32,33,34],
       [41,42,43,44],
       [51,52,53,54],
       [61,62,63,64],
       [71,72,73,74]]
    y=[1,1,0,0,1,1,0,0]
    
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=0)  #切分  为原始数据集大小的  40% 
    print('不使用分层抽样')
    print('X_train',X_train)
    print('X_test',X_test)
    print('y_train',y_train)
    print('y_test',y_test)
    
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=0,stratify=y)  #切分  为原始数据集大小的  40% 
    print('使用分层抽样  stratify')
    print('X_train',X_train)
    print('X_test',X_test)
    print('y_train',y_train)
    print('y_test',y_test)

test_train_test_split()

不使用分层抽样
X_train [[31, 32, 33, 34], [1, 2, 3, 4], [51, 52, 53, 54], [41, 42, 43, 44]]
X_test [[61, 62, 63, 64], [21, 22, 23, 24], [11, 12, 13, 14], [71, 72, 73, 74]]
y_train [0, 1, 1, 1]
y_test [0, 0, 1, 0]
使用分层抽样  stratify
X_train [[41, 42, 43, 44], [61, 62, 63, 64], [1, 2, 3, 4], [71, 72, 73, 74]]
X_test [[21, 22, 23, 24], [31, 32, 33, 34], [11, 12, 13, 14], [51, 52, 53, 54]]
y_train [1, 0, 1, 0]
y_test [0, 0, 1, 1]


In [2]:
def test_KFold():
    '''
    测试  KFold 的用法
    
    '''
    X=np.array([[1,2,3,4],
       [11,12,13,14],
       [21,22,23,24],
       [31,32,33,34],
       [41,42,43,44],
       [51,52,53,54],
       [61,62,63,64],
       [71,72,73,74]])
    y=np.array([1,1,0,0,1,1,0,0])
    
    folder=KFold(n_splits=4,random_state=0,shuffle=False)  #切分之前不混洗数据集
    print('不混洗数据集')
    for train_index,test_index in folder.split(X,y):
        print('train_index',train_index)
        print('test_index',test_index)
        print('x_train',X[train_index])
        print('x_test',X[test_index])
        print('    ')
        
    print('混洗数据集')
    shuffle_folder=KFold(n_splits=3,random_state=0,shuffle=True)
    for train_index,test_index in folder.split(X,y):
        print('train_index',train_index)
        print('test_index',test_index)
        print('x_train',X[train_index])
        print('x_test',X[test_index])
        print('    ') 

test_KFold()

不混洗数据集
train_index [2 3 4 5 6 7]
test_index [0 1]
x_train [[21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]]
x_test [[ 1  2  3  4]
 [11 12 13 14]]
    
train_index [0 1 4 5 6 7]
test_index [2 3]
x_train [[ 1  2  3  4]
 [11 12 13 14]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]]
x_test [[21 22 23 24]
 [31 32 33 34]]
    
train_index [0 1 2 3 6 7]
test_index [4 5]
x_train [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [61 62 63 64]
 [71 72 73 74]]
x_test [[41 42 43 44]
 [51 52 53 54]]
    
train_index [0 1 2 3 4 5]
test_index [6 7]
x_train [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]]
x_test [[61 62 63 64]
 [71 72 73 74]]
    
混洗数据集
train_index [2 3 4 5 6 7]
test_index [0 1]
x_train [[21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]
 [51 52 53 54]
 [61 62 63 64]
 [71 72 73 74]]
x_test [[ 1  2  3  4]
 [11 12 13 14]]
    
train_index [0 1 4 5 6 7]
test_index [2 3]
x_train [[ 1  2  3 

In [3]:
# stratifiedKFold  分层采样
import numpy as np
def test_StratifiedKFold():
    '''
    测试   stratifiedKFold 的用法
    
    :return None
    '''
    X=np.array([[1,2,3,4],
                [11,12,13,14],
                [21,22,23,24],
                [31,32,33,34],
                [41,42,43,44],
                [51,52,53,54],
                [61,62,63,64],
                [71,72,73,74]
                ])
    y=np.array([1,1,0,0,1,1,0,0])
    
    folder=KFold(n_splits=4,random_state=0,shuffle=False) #无分层采样的  
    stratified_folder=StratifiedKFold(n_splits=4,random_state=0,shuffle=False)
    for train_index,test_index in folder.split(X,y):
        print('Train Index:',train_index)
        print('test Index:',test_index)
        print('y_train:',y[train_index])
        print('y_test:',y[test_index])
        
    
    print('切分后的数据')
    for train_index,test_index in stratified_folder.split(X,y):
        print('Train Index:',train_index)
        print('test Index:',test_index)
        print('y_train:',y[train_index])
        print('y_test:',y[test_index])
        
        
test_StratifiedKFold()

Train Index: [2 3 4 5 6 7]
test Index: [0 1]
y_train: [0 0 1 1 0 0]
y_test: [1 1]
Train Index: [0 1 4 5 6 7]
test Index: [2 3]
y_train: [1 1 1 1 0 0]
y_test: [0 0]
Train Index: [0 1 2 3 6 7]
test Index: [4 5]
y_train: [1 1 0 0 0 0]
y_test: [1 1]
Train Index: [0 1 2 3 4 5]
test Index: [6 7]
y_train: [1 1 0 0 1 1]
y_test: [0 0]
切分后的数据
Train Index: [1 3 4 5 6 7]
test Index: [0 2]
y_train: [1 0 1 1 0 0]
y_test: [1 0]
Train Index: [0 2 4 5 6 7]
test Index: [1 3]
y_train: [1 0 1 1 0 0]
y_test: [1 0]
Train Index: [0 1 2 3 5 7]
test Index: [4 6]
y_train: [1 1 0 0 1 0]
y_test: [1 0]
Train Index: [0 1 2 3 4 6]
test Index: [5 7]
y_train: [1 1 0 0 1 0]
y_test: [1 0]


In [6]:
def test_LeaveOneOut():
    '''
    测试  LeaveOneOut  的用法
    '''
    X=np.array([[1,2,3,4],
                [11,12,13,14],
                [21,22,23,24],
                [31,32,33,34]])
    y=np.array([1,1,0,0])
    loo=LeaveOneOut()
    
    for train_index,test_index in loo.split(X):
        print('Train:',train_index,'Test:',test_index)
        X_train,X_test=X[train_index],X[test_index]
        y_train,y_test=y[train_index],y[test_index]
        print('留一后的训练与测试数据:',X_train,X_test)
        print('留一后的训练与测试标签:',y_train,y_test)
        
test_LeaveOneOut()

Train: [1 2 3] Test: [0]
留一后的训练与测试数据: [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] [[1 2 3 4]]
留一后的训练与测试标签: [1 0 0] [1]
Train: [0 2 3] Test: [1]
留一后的训练与测试数据: [[ 1  2  3  4]
 [21 22 23 24]
 [31 32 33 34]] [[11 12 13 14]]
留一后的训练与测试标签: [1 0 0] [1]
Train: [0 1 3] Test: [2]
留一后的训练与测试数据: [[ 1  2  3  4]
 [11 12 13 14]
 [31 32 33 34]] [[21 22 23 24]]
留一后的训练与测试标签: [1 1 0] [0]
Train: [0 1 2] Test: [3]
留一后的训练与测试数据: [[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]] [[31 32 33 34]]
留一后的训练与测试标签: [1 1 0] [0]


In [5]:
def test_cross_val_score():
    '''
    测试 cross_val_score 的用法
    
    将数据集 折成  cv=10   ->  kfold
    '''
    from sklearn.datasets import load_digits    #手写数字识别
    from sklearn.svm import LinearSVC   #分类器
    
    digits=load_digits()  #加载用于分类问题的数据集
    X=digits.data
    y=digits.target 
    #   LinearSVC  学习器必须要有 score
    result=cross_val_score(LinearSVC( ),X,y,cv=10)
    print('cross_val_score  is:',result)

test_cross_val_score()

cross_val_score  is: [ 0.9027027   0.93442623  0.87845304  0.88888889  0.92178771  0.94413408
  0.97765363  0.94382022  0.86440678  0.92045455]


# 自定义实现采样

### 随机采样

#### 1.无放回采样

In [14]:
import random
def RandomSampling(dataMat,number):
    '''
    无放回采样
    '''
    try:
        slice =random.sample(dataMat,number)
        return slice
    except:
        print('sample larger than populartion')

In [8]:
data=[          [1,2,3,4],
                [11,12,13,14],
                [21,22,23,24],
                [31,32,33,34],
                [41,42,43,44],
                [51,52,53,54],
                [61,62,63,64],
                [71,72,73,74]]
RandomSampling(data,7)

[[11, 12, 13, 14],
 [71, 72, 73, 74],
 [1, 2, 3, 4],
 [51, 52, 53, 54],
 [41, 42, 43, 44],
 [31, 32, 33, 34],
 [21, 22, 23, 24]]

#### 2.有放回采样

In [9]:
def RepetitionRandomSampling(dataMat,number):
    '''
    放回采样
    '''
    sample=[]
    for i in range(number):
        sample.append(dataMat[random.randint(0,len(dataMat)-1)])
    return sample

RepetitionRandomSampling(data,7)

[[1, 2, 3, 4],
 [41, 42, 43, 44],
 [31, 32, 33, 34],
 [21, 22, 23, 24],
 [1, 2, 3, 4],
 [61, 62, 63, 64],
 [11, 12, 13, 14]]

#### 3.分层采样

In [17]:
def StratifiedSampling(dataMat1,dataMat2,dataMat3,number):
    sample=[]
    num=number//3
    sample.append(RandomSampling(dataMat1,num))
    sample.append(RandomSampling(dataMat2,num))
    sample.append(RandomSampling(dataMat3,num))
    return sample

In [18]:
data1=[1,2,3,4]
data2=[6,7,8,9]
data3=[10,11,12,13]
StratifiedSampling(data1,data2,data3,6)

[[3, 4], [7, 8], [12, 13]]

#### 4.系统采样

In [19]:
def SystematicSampling(dataMat,number):
    '''
    系统采样
    系统采用又称为等距采样
    '''
    length=len(dataMat)
    k=length//number
    sample=[]
    i=0
    if k>0:
        while len(sample)!=number:
            sample.append(dataMat[0+i*k])
            i+=1
        return sample
    else:
        return RandomSampling(dataMat,number)

In [20]:
SystematicSampling(data,3)

[[1, 2, 3, 4], [21, 22, 23, 24], [41, 42, 43, 44]]

### 二元化

In [22]:
from sklearn.preprocessing import Binarizer

#二元化
def test_Binarizer():
    '''
    测试 Binarizer 的使用方法
    '''
    X=[[1,2,3,4,5],
        [5,4,3,2,1],
       [3,3,3,3,3],
       [1,1,1,1,1]]
    print("转换前:",X)
    binarizer=Binarizer(threshold=2.5)   #阈值  2.5
    print('转换后：',binarizer.transform(X) )
    
test_Binarizer()

转换前: [[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [3, 3, 3, 3, 3], [1, 1, 1, 1, 1]]
转换后： [[0 0 1 1 1]
 [1 1 1 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]]


### 独热编码

In [24]:
from sklearn.preprocessing import OneHotEncoder
def test_OneHotEncoder():
    '''
    OneHotEncoder  的用法
    '''
    X=[[1,2,3,4,5],
        [5,4,3,2,1],
       [3,3,3,3,3],
       [1,1,1,1,1]]
    print('before transform:',X)
    encoder=OneHotEncoder(sparse=True)    #假如是 True  每一个值都是一个稀疏矩阵
    encoder.fit(X)
    
    #激活特征 如原始数据的某个属性的某个取值在转换后数据的第i个属性中激活
    print('活跃的特征值：',encoder.active_features_)
    print('目录特征值：',encoder.feature_indices_)
    
    print('n_values_:',encoder.n_values_)
    print('after transform:',encoder.transform([[5,2,3,4,5]]))
    
test_OneHotEncoder()

before transform: [[1, 2, 3, 4, 5], [5, 4, 3, 2, 1], [3, 3, 3, 3, 3], [1, 1, 1, 1, 1]]
活跃的特征值： [ 1  3  5  7  8  9 10 12 14 16 17 18 19 21 23 25]
目录特征值： [ 0  6 11 15 20 26]
n_values_: [6 5 4 5 6]
after transform:   (0, 15)	1.0
  (0, 12)	1.0
  (0, 8)	1.0
  (0, 4)	1.0
  (0, 2)	1.0
