# 数据合并 concat

In [13]:
import numpy as np
import pandas as pd

#### NumPy的concat

In [2]:
arr1=np.random.randint(0,10,(3,4))
arr2=np.random.randint(0,10,(3,4))

print(arr1)
print(arr2)

[[7 3 5 0]
 [6 9 6 9]
 [8 7 9 6]]
[[5 9 1 3]
 [1 4 4 3]
 [0 7 9 3]]


In [3]:
np.concatenate([arr1,arr2])  #axis=0   列

array([[7, 3, 5, 0],
       [6, 9, 6, 9],
       [8, 7, 9, 6],
       [5, 9, 1, 3],
       [1, 4, 4, 3],
       [0, 7, 9, 3]])

In [4]:
np.concatenate([arr1,arr2], axis=1)  #axis=1  行

array([[7, 3, 5, 0, 5, 9, 1, 3],
       [6, 9, 6, 9, 1, 4, 4, 3],
       [8, 7, 9, 6, 0, 7, 9, 3]])

#### Series上的concat

In [5]:
#index 没有重复的情况
ser_obj1=pd.Series(np.random.randint(0,10,5),index=range(0,5) )
ser_obj2=pd.Series(np.random.randint(0,10,4),index=range(5,9) )
ser_obj3=pd.Series(np.random.randint(0,10,3),index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)


0    0
1    4
2    6
3    7
4    3
dtype: int32
5    9
6    4
7    2
8    7
dtype: int32
9     1
10    6
11    3
dtype: int32


In [6]:
pd.concat([ser_obj1,ser_obj2,ser_obj3])

0     0
1     4
2     6
3     7
4     3
5     9
6     4
7     2
8     7
9     1
10    6
11    3
dtype: int32

In [7]:
pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1)

0    1    2
0   0.0  NaN  NaN
1   4.0  NaN  NaN
2   6.0  NaN  NaN
3   7.0  NaN  NaN
4   3.0  NaN  NaN
5   NaN  9.0  NaN
6   NaN  4.0  NaN
7   NaN  2.0  NaN
8   NaN  7.0  NaN
9   NaN  NaN  1.0
10  NaN  NaN  6.0
11  NaN  NaN  3.0

In [8]:
#index 有重复的东西
ser_obj1=pd.Series(np.random.randint(0,10,5),index=range(5) )
ser_obj2=pd.Series(np.random.randint(0,10,4),index=range(4) )
ser_obj3=pd.Series(np.random.randint(0,10,3),index=range(3))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)

0    1
1    2
2    8
3    4
4    3
dtype: int32
0    2
1    6
2    0
3    1
dtype: int32
0    2
1    9
2    0
dtype: int32


In [9]:
pd.concat([ser_obj1,ser_obj2,ser_obj3])

0    1
1    2
2    8
3    4
4    3
0    2
1    6
2    0
3    1
0    2
1    9
2    0
dtype: int32

In [10]:
pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1,join='inner')   #列变行  ，行变列  且使用内联   相当于求交集

0  1  2
0  1  2  2
1  2  6  9
2  8  0  0

In [11]:
pd.concat([ser_obj1,ser_obj2,ser_obj3],axis=1,join='outer')  ##列变行  ，行变列  且使用外联   相当于求并集

0    1    2
0  1  2.0  2.0
1  2  6.0  9.0
2  8  0.0  0.0
3  4  1.0  NaN
4  3  NaN  NaN

In [16]:
df_obj1=pd.DataFrame(np.random.randint(0,10,(3,2)),index=['a','b','c'],
                     columns=['A','B'])
df_obj2=pd.DataFrame(np.random.randint(0,10,(2,2)),index=['a','b'],
                     columns=['C','D'])

print(df_obj1)
print(df_obj2)

   A  B
a  4  6
b  0  5
c  9  4
   C  D
a  5  2
b  1  0


In [17]:
pd.concat([df_obj1,df_obj2])

A    B    C    D
a  4.0  6.0  NaN  NaN
b  0.0  5.0  NaN  NaN
c  9.0  4.0  NaN  NaN
a  NaN  NaN  5.0  2.0
b  NaN  NaN  1.0  0.0

In [18]:
pd.concat([df_obj1,df_obj2],axis=1)

A  B    C    D
a  4  6  5.0  2.0
b  0  5  1.0  0.0
c  9  4  NaN  NaN