# Pandas基本数据结构

In [1]:
import pandas as pd

In [2]:
#Series 是一个类数组的数据结构  同时带有标签（label） 或者说索引（index）

In [4]:
#通过list构建Series
ser_obj=pd.Series( range(10,30)  )
print(type(ser_obj))

<class 'pandas.core.series.Series'>


In [5]:
#获取数据
print(ser_obj.values)

#获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
RangeIndex(start=0, stop=20, step=1)


In [6]:
#预览数据
print(ser_obj.head(3))

0    10
1    11
2    12
dtype: int32


In [7]:
print(ser_obj.tail(3))

17    27
18    28
19    29
dtype: int32


In [8]:
ser_obj.head()  #默认前5条

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [9]:
#通过索引来获取数据
print(ser_obj[0])
print(ser_obj[10])

10
20


In [10]:
#索引与数据的对应关系仍保持在数组运算的结果中
print(ser_obj*2)    #每个元素乘以2
print(ser_obj>25)   #判断每个元素是否大于25  返回值是  True  False

0     20
1     22
2     24
3     26
4     28
5     30
6     32
7     34
8     36
9     38
10    40
11    42
12    44
13    46
14    48
15    50
16    52
17    54
18    56
19    58
dtype: int32
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18     True
19     True
dtype: bool


In [12]:
#通过dict构建Series  此时dict中的键作位index    值做value 且根据键自动排序
year_data={2007:33,2001:17.8,2002:20.1,2003:16.6}
ser_obj2=pd.Series(year_data)
print(ser_obj2.head())
print(ser_obj2.index)
print(ser_obj2.values)

2001    17.8
2002    20.1
2003    16.6
2007    33.0
dtype: float64
Int64Index([2001, 2002, 2003, 2007], dtype='int64')
[ 17.8  20.1  16.6  33. ]


In [13]:
#name属性  用于给Series及它的索引命名
ser_obj2.name='测试数据集'
ser_obj2.index.name='year'
print(ser_obj2)

year
2001    17.8
2002    20.1
2003    16.6
2007    33.0
Name: 测试数据集, dtype: float64


In [15]:
import numpy as np

#1.通过ndarray构建DataFrame
#randn()  从标准正态分布中返回一个或多个样本值
array=np.random.randn(5,4)  # 5行4列
print(array)

df_obj=pd.DataFrame(array)
print(df_obj.head())

[[-1.2081783   1.15021712  0.27211575 -0.58274508]
 [ 0.30968447  0.13456216  1.28838123  0.70719378]
 [-0.86374432  0.13294968  0.81983891  0.27258811]
 [-0.07331036  1.32108825  0.59575186  0.29821662]
 [-1.00480024 -3.65921497  0.63711836  0.59385888]]
          0         1         2         3
0 -1.208178  1.150217  0.272116 -0.582745
1  0.309684  0.134562  1.288381  0.707194
2 -0.863744  0.132950  0.819839  0.272588
3 -0.073310  1.321088  0.595752  0.298217
4 -1.004800 -3.659215  0.637118  0.593859


In [16]:
# 通过dict构建DataFrame  dataframe中的每个列的数据可以是不同的类型
dict_data={
            'A':1,
            'B':pd.Timestamp('20161217'),
            'C':pd.Series(1,index=list(range(4)),dtype='float32'),
            'D':np.array([3]*4,dtype='int32'),
            'E':pd.Categorical(['Python','Java','C++','c#']),
            'F':'ChinaHadoop'
            }
df_obj2=pd.DataFrame(dict_data)
print(df_obj2.head())

   A          B    C  D       E            F
0  1 2016-12-17  1.0  3  Python  ChinaHadoop
1  1 2016-12-17  1.0  3    Java  ChinaHadoop
2  1 2016-12-17  1.0  3     C++  ChinaHadoop
3  1 2016-12-17  1.0  3      c#  ChinaHadoop


In [17]:
#通过索引来获取数据
print(df_obj2['A'])
print(type(df_obj2['A']  )  )

print(df_obj2.A)

0    1
1    1
2    1
3    1
Name: A, dtype: int64
<class 'pandas.core.series.Series'>
0    1
1    1
2    1
3    1
Name: A, dtype: int64


In [18]:
#增加列
df_obj2['G']=df_obj2["D"]+4
print(df_obj2.head())

   A          B    C  D       E            F  G
0  1 2016-12-17  1.0  3  Python  ChinaHadoop  7
1  1 2016-12-17  1.0  3    Java  ChinaHadoop  7
2  1 2016-12-17  1.0  3     C++  ChinaHadoop  7
3  1 2016-12-17  1.0  3      c#  ChinaHadoop  7


# 索引对象  index

In [19]:
print(type(ser_obj.index))
print(type(df_obj2.index))

print(df_obj2.index)

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'pandas.core.indexes.numeric.Int64Index'>
Int64Index([0, 1, 2, 3], dtype='int64')


In [20]:
#索引对象不可以变  操作失败
df_obj2.index[0]=2

TypeError: Index does not support mutable operations